version: '3.1'

services:

  db:
    build: .
    restart: 'no'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5001:5432


  adminer:
    image: adminer
    restart: 'no'
    ports:
      - 8080:8080
